# Generated by Django 4.1.4 on 2023-03-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('dinner_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('dinner_price', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('lunch_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('lunch_price', models.CharField(max_length=150)),
            ],
        ),
    ]
