# Generated by Django 4.1.4 on 2023-03-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjango', '0002_dinner_lunch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('snacks_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('snacks_price', models.CharField(max_length=150)),
            ],
        ),
    ]
