# Generated by Django 4.1.4 on 2023-03-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjango', '0003_snacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('meal', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('guests', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_coupon_price', models.CharField(max_length=150)),
            ],
        ),
    ]
